### ISSUE TITLE
Bug report: unable to push/import large repo

### ISSUE THREAD

**Issue by stepbrobd** [charmbracelet/soft-serve#348]
**Describe the bug**

"Connection to <soft-serve instance url> closed by remote host." when trying to push/import large repo.

`charmcli/soft-serve:v0.5.5` hosted on fly.io is not able to push/import a repo (a fork of nixpkgs, around 3.5GB), the vm specs are relatively acceptable:  shared-cpu-4x,  4GB RAM (https://fly.io/docs/about/pricing/).

Log:

```log
2023-07-25T08:07:26Z app[17811104a56e58] bos [info]2023-07-25 08:07:26 ERRO sqlite: failed to clone repository
2023-07-25T08:07:26Z app[17811104a56e58] bos [info]  err=
2023-07-25T08:07:26Z app[17811104a56e58] bos [info]  │ kill process: os: process already finished - fatal: early EOF
2023-07-25T08:07:26Z app[17811104a56e58] bos [info]  mirror=false remote=https://github.com/stepbrobd/nixpkgs path=/data/repos/stepbrobd/nixpkgs.git
```

**To Reproduce**

1. Use any soft-serve instance, try importing nixpkgs by using: `ssh <instance url> repo import nixpkgs https://github.com/nixos/nixpkgs`
2. Wait about 90sec, your terminal should print out `Connection to <instance url> closed by remote host.`

**Expected behavior**

soft-serve should successfully push/import a large repo.

**Screenshots**

<img width="773" alt="Screenshot 2023-07-24 at 22 35 20" src="https://github.com/charmbracelet/soft-serve/assets/81826728/b8861b7c-407f-4319-9c0f-b73dfda5e0b3">
<img width="773" alt="Screenshot 2023-07-24 at 22 34 03" src="https://github.com/charmbracelet/soft-serve/assets/81826728/5a4a13ca-889b-4144-81b2-df0fbeb7f060">
<img width="773" alt="Screenshot 2023-07-24 at 22 34 11" src="https://github.com/charmbracelet/soft-serve/assets/81826728/8c413668-ba52-4864-a35f-db62a156c433">

**Environment (please complete the following information):**

 - OS: linux, firecracker vm, fly.io
 - Terminal: iterm2
 - Version: `charmcli/soft-serve:v0.5.5` hosted on fly.io

**Additional context**

N/A

**Comment by aymanbagabas** [comment]
Hi @stepbrobd, could you provide your Soft Serve config file?

**Comment by stepbrobd** [comment]
Thanks for getting back! Here's what I have:

```toml filename="fly.toml"
# Git.StepBroBD.com
app = "<app name>"
primary_region = "<app region>"
kill_signal = "SIGINT"
kill_timeout = "10s"

# Roll back to the previously running version if failed
[experimental]
auto_rollback = true

# Soft Serve
[build]
image = "charmcli/soft-serve:v0.5.5"

# Mount volume
[[mounts]]
source = "data"
destination = "/data"

# Environment variables
[env]
SOFT_SERVE_DATA_PATH = "/data"
SOFT_SERVE_NAME = "<name>"
SOFT_SERVE_INITIAL_ADMIN_KEYS = "<ssh public key>"
SOFT_SERVE_SSH_PUBLIC_URL = "ssh://<fqdn>"
SOFT_SERVE_HTTP_PUBLIC_URL = "https://<fqdn>"
SOFT_SERVE_GIT_LISTEN_ADDR = "0.0.0.0:9418"
SOFT_SERVE_SSH_LISTEN_ADDR = "0.0.0.0:23231"
SOFT_SERVE_HTTP_LISTEN_ADDR = "0.0.0.0:23232"

# Prometheus
[[services]]
protocol = "tcp"
internal_port = 23233

[[services.ports]]
port = 9090

[services.concurrency]
type = "connections"
soft_limit = 25
hard_limit = 50

# Git
[[services]]
protocol = "tcp"
internal_port = 9418

[[services.ports]]
port = 9418

[services.concurrency]
type = "connections"
soft_limit = 25
hard_limit = 50

# SSH
[[services]]
protocol = "tcp"
internal_port = 23231

[services.concurrency]
type = "connections"
soft_limit = 25
hard_limit = 50

[[services.ports]]
port = 22

# HTTP/HTTPS
[http_service]
internal_port = 23232
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 75
hard_limit = 100
```

All the configs are done with the environment variables.
