### ISSUE TITLE
Unable to init my "admin" account

### ISSUE THREAD

**Issue by 3sky** [charmbracelet/soft-serve#497]
**Describe the bug**
I just unable to use ssh-keypair for my installation. 

**To Reproduce**
1. I'm using docker-compose on my NAS.
```yaml
---
version: "3.1"
services:
  soft-serve:
     environment:
        - SOFT_SERVE_INITIAL_ADMIN_KEYS='ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxYZEBNRLXmuign6ZgNbmaSK7cnQAgFpx8cCscoqseA local'
    image: charmcli/soft-serve:v0.7.4
    container_name: soft-serve
    volumes:
      - /path/to/data:/soft-serve
    ports:
      - 23231:23231
      - 23232:23232
      - 23233:23233
      - 9418:9418
    restart: unless-stopped
   ```
2. Adding `SOFT_SERVE_INITIAL_ADMIN_KEYS` as env as above, or I'm trying to use in config.yaml:
```yaml
initial_admin_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJxYZEBNRLXmuign6ZgNbmaSK7cnQAgFpx8cCscoqseA local"
 ```

3. Then after container restart i'm trying to ssh my instance:
```console
$ ssh 192.168.0.33 -p 23231 -i ~/.ssh/id_ed25519_local info
Error: user not found
```
4. With regular ssh:

```console
$ ssh 192.168.0.33 -p 23231 -i ~/.ssh/id_ed25519_local
Permission denied (publickey,keyboard-interactive).
```

**Expected behavior**

Ability to operate with my instance as admin user, not sure if documentation if out-dated, or I missing something important here.

**Environment (please complete the following information):**
 - OS: Linux(Synology NAS)
 - Version v0.7.4
