### ISSUE TITLE
Unable to connect to a Soft Serve TUI

### ISSUE THREAD

**Issue by Infinidoge** [charmbracelet/soft-serve#72]
# The Problem

When attempting to connect to a TUI that runs Soft Serve (such as `git.charm.sh`, or `localhost:23231` when running `soft` locally, the SSH session immediately exists after initially connecting.

Looking at the logs for the `soft` program, it appears to output a shell script that should run on the client. Looking at the verbose logs for SSH, the shell script is only partially received and the SSH connection then closes. (Notably, the SSH connection exits without producing an error.)

Working with `git` on the server works as expected. `git clone ssh://localhost:23231/config` succeeded, and I was able to edit and push a new configuration up with no issues.

## Host Information
```yaml
OS: NixOS 22.05 (Unstable)
Kernel: Linux 5.16.2
Shell: ZSH 5.8
SSH Version: OpenSSH 8.8p1
Terminal: kitty
$TERM: xterm-kitty
```

## Screenshots & Logs
Attempting to connect (`-S none` to disable multiplexed connection):
![image](https://user-images.githubusercontent.com/22727114/150992385-98f7d18e-b584-435d-9c14-307557c48a80.png)

SSH log (with `-v`):
http://ix.io/3Nu2

Soft log: 
http://ix.io/3Nu3
